services:
  op-node:
    image: ghcr.io/uminetwork/op-node:${UMI_TAG:-latest}
    build:
      dockerfile: docker/shared/Dockerfile
      target: op-node
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - localnet
    volumes:
      - ./docker/shared/volume:/volume/shared

  op-batcher:
    image: ghcr.io/uminetwork/op-batcher:${UMI_TAG:-latest}
    build:
      dockerfile: docker/shared/Dockerfile
      target: op-batcher
    networks:
      - localnet
    volumes:
      - ./docker/shared/volume:/volume/shared

  op-proposer:
    image: ghcr.io/uminetwork/op-proposer:${UMI_TAG:-latest}
    build:
      dockerfile: docker/shared/Dockerfile
      target: op-proposer
    networks:
      - localnet
    volumes:
      - ./docker/shared/volume:/volume/shared

  op-move:
    image: ghcr.io/uminetwork/op-move:${UMI_TAG:-latest}
    build:
      dockerfile: docker/op-move/Dockerfile
      args:
        - RUST_TOOLCHAIN
    environment:
      OP_MOVE_AUTH_JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
      OP_MOVE_DB_PURGE: ${OP_MOVE_DB_PURGE:-false}
    networks:
      - localnet
    depends_on:
      - op-node
    volumes:
      - ./docker/shared/volume:/volume/shared
      - ./docker/op-move/volume:/volume/db
    ports:
      - "8545:8545"
      - "9000:9000"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://0.0.0.0:8545/",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  geth:
    image: ghcr.io/uminetwork/geth:${UMI_TAG:-latest}
    build:
      dockerfile: docker/shared/Dockerfile
      target: geth
    networks:
      - localnet
    volumes:
      - ./docker/shared/volume:/volume/shared
    ports:
      - "58138:58138"

networks:
  localnet:
    external: true
