services:
  foundry:
    image: moved-foundry:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.foundry
    deploy:
      replicas: 0

  optimism:
    image: moved-optimism:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.optimism
    depends_on:
      - foundry
    deploy:
      replicas: 0
    networks:
      - auth-network

  op-node:
    image: moved-op-node:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-node
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - auth-network
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-batcher:
    image: moved-op-batcher:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-batcher
    networks:
      - auth-network
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-proposer:
    image: moved-op-proposer:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-proposer
    networks:
      - auth-network
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-geth:
    image: moved-op-geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-geth
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - auth-network
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-move:
    image: moved-op-move:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-move
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
      OP_GETH_ADDR: "op-geth"
    networks:
      - auth-network
    volumes:
      - ./docker/volumes/shared:/volume/shared
      - ./docker/volumes/db:/volume/db
    ports:
      - "8545:8545"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://0.0.0.0:8545/',
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  geth:
    image: moved-geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.geth
    networks:
      - auth-network
    depends_on:
      - foundry
    ports:
      - "58138:58138"

networks:
  auth-network:
    external: true
