[package]
name = "umi-load-testing"
description = "Load testing for the op-move application."
version.workspace = true
edition.workspace = true

[features]
default = []

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
tempfile.workspace = true
tokio.workspace = true
umi-server-args.workspace = true

[dev-dependencies]
