# First build all the dependencies
FROM golang:1.22-alpine AS optimism

# Declare argument for target architecture supplied automatically by the build system
ARG TARGETARCH

RUN \
  # Install build dependencies
  apk add --no-cache git make bash wget \
  # Download and extract foundry binaries
  && \
    if [ "$TARGETARCH" = "amd64" ]; then \
      wget https://github.com/foundry-rs/foundry/releases/download/v1.2.3/foundry_v1.2.3_alpine_amd64.tar.gz && \
      tar -xzf foundry_v1.2.3_alpine_amd64.tar.gz; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
      wget https://github.com/foundry-rs/foundry/releases/download/v1.2.3/foundry_v1.2.3_alpine_arm64.tar.gz && \
      tar -xzf foundry_v1.2.3_alpine_arm64.tar.gz; \
    else \
      echo "Unsupported architecture"; exit 1; \
    fi \
  # Clone optimism at specific commit
  && git clone https://github.com/ethereum-optimism/optimism /volume \
  && git --work-tree /volume --git-dir /volume/.git checkout f2e5a7a5 \
  # Build optimism binaries and files required for op-node startup
  && make --directory /volume cannon-prestate op-node op-batcher op-proposer \
  # Install forge dependencies for contracts
  && ./forge install --root /volume/packages/contracts-bedrock \
  # Move build artifacts to the root directory
  && mv \
    # Only the foundry binaries we need
    forge \
    cast \
    # Only the built binaries we need
    /volume/op-node/bin/op-node \
    /volume/op-batcher/bin/op-batcher \
    /volume/op-proposer/bin/op-proposer \
    # Files required for op-node startup
    /volume/op-program/bin/prestate.json \
    /volume/op-program/bin/meta.json \
    /volume/op-program/bin/prestate-proof.json \
    # Contracts and dependencies needed for OP Stack deployment
    /volume/packages/contracts-bedrock \
    # Git directory to keep the right commit checked out
    /volume/.git / \
  # Clean up
  && rm -rf $(ls -d /* /etc/* | grep -v \
    -e ^/cast$ -e ^/forge$ -e ^/op-node$ -e ^/op-batcher$ -e ^/op-proposer$ \
    -e ^/prestate.json$ -e ^/meta.json$ -e ^/prestate-proof.json$ \
    -e ^/contracts-bedrock$ -e ^/.git$ \
    -e ^/sys$ -e ^/proc$ -e ^/dev -e ^/etc$ -e ^/etc/hosts$ -e ^/etc/resolv.conf$ \
  )

# Switch to clean image
FROM alpine:3.21.2 AS op-proposer
WORKDIR /volume

RUN \
  # bash required by wait-for-it
  # jq required by entrypoint to parse L2_ORACLE_PROXY
  apk add --no-cache bash jq \
  # Clean up
  && rm -rf /tmp/* /var/cache/apk/*

# Copy built binary from build image
COPY --from=optimism /op-proposer /usr/local/bin/op-proposer

# Copy entrypoint
COPY docker/op-proposer.sh entrypoint.sh
COPY .env .env
COPY docker/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x entrypoint.sh /usr/local/bin/wait-for-it

ENTRYPOINT [ "/volume/entrypoint.sh" ]

# Switch to clean image
FROM alpine:3.21.2 AS op-batcher
WORKDIR /volume

RUN \
  # bash required by wait-for-it
  apk add --no-cache bash \
  # Clean up
  && rm -rf /tmp/* /var/cache/apk/*

# Copy built binary from build image
COPY --from=optimism /op-batcher /usr/local/bin/op-batcher

# Copy entrypoint
COPY docker/op-batcher.sh entrypoint.sh
COPY .env .env
COPY docker/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x entrypoint.sh /usr/local/bin/wait-for-it

ENTRYPOINT [ "/volume/entrypoint.sh" ]

# Switch to clean image
FROM alpine:3.21.2 AS op-node
WORKDIR /volume

RUN \
  # jq required at least by optimism deploy script
  apk add --no-cache clang lld curl build-base linux-headers git bash jq \
  # Clean up
  && rm -rf /tmp/* /var/cache/apk/*

# Copy entrypoint
COPY docker/op-node.sh entrypoint.sh

# Copy genesis config generator
COPY server/src/tests/config.sh config.sh

# Copy ENV file that include Optimism wallet addresses
COPY .env .env
COPY docker/wait-for-it.sh /usr/local/bin/wait-for-it

# Grant run privileges to copied scripts
RUN chmod +x entrypoint.sh config.sh /usr/local/bin/wait-for-it

# Copy only the specific Solidity compiler versions needed
COPY --from=ethereum/solc:0.8.15 /usr/bin/solc /root/.svm/0.8.15/solc-0.8.15
COPY --from=ethereum/solc:0.8.19 /usr/bin/solc /root/.svm/0.8.19/solc-0.8.19
COPY --from=ethereum/solc:0.8.25 /usr/bin/solc /root/.svm/0.8.25/solc-0.8.25

# Copy built binary from build image and other dependencies
COPY --from=optimism /op-node /usr/local/bin/op-node
COPY --from=optimism /contracts-bedrock /volume/packages/contracts-bedrock
COPY --from=optimism /.git /volume/.git
COPY --from=optimism /prestate.json /volume/op-program/bin/prestate.json
COPY --from=optimism /meta.json /volume/op-program/bin/meta.json
COPY --from=optimism /prestate-proof.json /volume/op-program/bin/prestate-proof.json
COPY --from=optimism /cast /usr/local/bin/cast
COPY --from=optimism /forge /usr/local/bin/forge

ENTRYPOINT [ "/volume/entrypoint.sh" ]
