# Declare variable for Rust toolchain version which should be filled with `rust-toolchain` file contents
ARG RUST_TOOLCHAIN="1.85.1"

# Start from a container that has workspace rust toolchain
FROM rust:${RUST_TOOLCHAIN}-alpine AS build

# Set working directory
WORKDIR /volume

# Copy file with workspace rust toolchain
COPY rust-toolchain rust-toolchain

# Install build dependencies
RUN apk add --no-cache clang clang-dev lld curl build-base linux-headers git openssl-dev

# Add `cargo` to `PATH`
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy sources over to the image
COPY . .

# RocksDB breaks the build with libclang.so not found, point its location explicitly
ENV LIBCLANG_PATH="/usr/lib/llvm20/lib/libclang.so.20.1.8"

# Build release binary
RUN --mount=type=cache,target=/root/.cargo/registry \
  --mount=type=cache,target=/root/.cargo/git \
  --mount=type=cache,target=/volume/target \
  # RocksDB breaks the build with libclang.so not found https://github.com/apache/skywalking/issues/10439
  # Aptos-core breaks the build with `disable_lifo_slot` not found https://github.com/aptos-labs/aptos-core/issues/5655 \
  RUSTFLAGS="-C target-feature=-crt-static --cfg tokio_unstable" \
  cargo build --bin op-move --release --features storage \
  && mv target/release/op-move /volume/op-move

# Switch to clean image
FROM alpine:3.21.2 AS op-move
WORKDIR /volume

RUN \
  # Install run dependencies
  apk add --no-cache clang lld curl build-base linux-headers git openssl-dev \
  # Clean up
  && rm -rf /tmp/* /var/cache/apk/* \
  # Create directory that is used in relative paths to Move framework snapshot files
  && mkdir genesis

# Copy Move framework snapshot files into expected paths
COPY genesis/aptos.mrb genesis/aptos.mrb
COPY genesis/sui.mrb genesis/sui.mrb

# Copy L2 genesis config into expected path
COPY execution/src/tests/res/l2_genesis_tests.json server/src/tests/optimism/packages/contracts-bedrock/deployments/genesis.json
COPY execution/src/tests/res/bridged_tokens_test.json execution/src/tests/res/bridged_tokens_test.json

# Copy built binary
COPY --from=build /volume/op-move /volume/op-move

# Copy entrypoint
COPY docker/op-move.sh entrypoint.sh

# Grant run privileges to copied script
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "/volume/entrypoint.sh" ]
