# Docker embedded DNS
resolver 127.0.0.11 ipv6=off valid=5s;

server {
  listen 8545;

  location / {
    set $req_start_ms $msec;
    proxy_set_header X-Req-Start-Ms $req_start_ms;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # set dynamically to avoid it failing at startup
    set $upstream_host op-move;
    proxy_pass http://$upstream_host:8545;
  }
}
