use {
    crate::{client::UmiClient, config::LoadTestConfig},
    tokio::sync::broadcast,
};

mod client;
mod compile;
mod config;
mod loads;
mod run_server;
mod stats;

const CARGO_MANIFEST_DIR: &str = std::env!("CARGO_MANIFEST_DIR");

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = LoadTestConfig::new()?;
    let server_binary = config.binary_path().await?;
    let (stats_collector, stats_channel) = stats::StatsCollector::new(config.stats_dir.clone());

    // Spawn task for collecting stats generated by load testing
    let stats_collector_task = stats_collector.spawn();

    // Start `op-move` and wait for it to be ready.
    let mut umi_process = run_server::start(&server_binary, config.to_server_config()?)?;
    tokio::time::sleep(config.op_move_start_time).await;

    // Get the genesis block hash
    let genesis_block_hash = {
        let client = UmiClient::new(stats_channel.clone(), Some(config.jwt_secret()));
        let genesis = client.get_block_by_number(0).await?;
        genesis.0.header.hash
    };

    // Create shutdown channel to control graceful end to load test.
    let (shutdown, shutdown_rx) = broadcast::channel(1);

    // Spawn the block building job
    let block_build = loads::block_production::BlockProduction::new(
        genesis_block_hash,
        config.jwt_secret(),
        stats_channel.clone(),
        shutdown_rx,
    )
    .spawn();

    // Spawn balance check jobs
    let balance_checkers = loads::balance_checker::BalanceChecker::spawn_many(
        config.n_balance_checkers,
        stats_channel,
        shutdown.subscribe(),
    )
    .await?;

    tokio::time::sleep(config.load_test_duration).await;

    // Shutdown loads
    shutdown.send(()).ok();
    if let Err(e) = block_build.await {
        println!("WARN: failed to join block build task: {e:?}");
    }
    for handle in balance_checkers {
        if let Err(e) = handle.await {
            println!("WARN: failed to join balance checker task: {e:?}");
        }
    }

    // Shutdown `op-move`
    umi_process.kill().await?;

    // Wait for stats collector to finish before exiting the program.
    if let Err(e) = stats_collector_task.await {
        println!("WARN: failed to join stats collector task: {e:?}");
    }

    Ok(())
}
