name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - run: echo "TOOLCHAIN=$(cat rust-toolchain)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
      - name: Test
        run: cargo test -- --skip integration
      - name: Run flaky tests
        run: cargo test -- --ignored
        continue-on-error: true

  clippy:
    name: Clippy
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      # Make sure CI fails on all warnings, including Clippy lints
      RUSTFLAGS: "-Dwarnings --cfg tokio_unstable"
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - run: echo "TOOLCHAIN=$(cat rust-toolchain)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          components: clippy
      - uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: format
        run: cargo +nightly fmt -- --check
