name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx, a driver that supports cache export
        uses: docker/setup-buildx-action@v3

      - name: Restore cached Rust build artifacts
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: docker/op-move/Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build ${{ github.sha }}
        run: UMI_TAG=${{ github.sha }} docker compose -f docker-compose.yml -f .github/docker-compose.yml build --build-arg RUST_TOOLCHAIN=$(cat rust-toolchain)

      - name: Push ${{ github.sha }}
        run: UMI_TAG=${{ github.sha }} docker compose push

      - name: Tag latest
        run: docker compose build --build-arg RUST_TOOLCHAIN=$(cat rust-toolchain)

      - name: Push latest
        run: docker compose push
